### ISSUE TITLE
Exiting from the middle of the suite cripples caches

### ISSUE THREAD

**Issue by bopm** [avmnu-sng/rspec-tracer#39]
## Expected behavior

I would like RSpec Tracer to allow me to break from the middle of the suite using ByeBug exit.

## Actual behavior

If I exit in the middle of the suite, my caches are crippled and I need to remove them.

## Steps to reproduce the problem

Add byebug in any specs. Run suite, exit from buybug console.

```
(byebug) exit


Pending: (Failures listed here are expected and do not affect your suite's status)
...
RSpec tracer is generating reports
RSpec tracer reports written to <...>/rspec_tracer_cache/9d2558b01c8894c7c5dba273fbdcd589 (took 0.02917 seconds)
Traceback (most recent call last):
	8: from /Users/sergeymoiseev/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rspec-tracer-0.9.1/lib/rspec_tracer/defaults.rb:15:in `block in <top (required)>'
	7: from /Users/sergeymoiseev/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rspec-tracer-0.9.1/lib/rspec_tracer.rb:79:in `at_exit_behavior'
	6: from /Users/sergeymoiseev/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rspec-tracer-0.9.1/lib/rspec_tracer.rb:181:in `run_exit_tasks'
	5: from /Users/sergeymoiseev/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rspec-tracer-0.9.1/lib/rspec_tracer.rb:193:in `generate_reports'
	4: from /Users/sergeymoiseev/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rspec-tracer-0.9.1/lib/rspec_tracer.rb:193:in `new'
	3: from /Users/sergeymoiseev/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rspec-tracer-0.9.1/lib/rspec_tracer/html_reporter/reporter.rb:15:in `initialize'
	2: from /Users/sergeymoiseev/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rspec-tracer-0.9.1/lib/rspec_tracer/html_reporter/reporter.rb:58:in `format_examples'
	1: from /Users/sergeymoiseev/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rspec-tracer-0.9.1/lib/rspec_tracer/html_reporter/reporter.rb:58:in `each_pair'
/Users/sergeymoiseev/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rspec-tracer-0.9.1/lib/rspec_tracer/html_reporter/reporter.rb:64:in `block in format_examples': undefined method `[]' for nil:NilClass (NoMethodError)
Coverage report generated for RSpec to <...>/coverage. 2683 / 4858 LOC (55.23%) covered.
Lcov style coverage report generated for RSpec to <...>/coverage/lcov/coverage.lcov
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected

$ bundle exec rspec
Started RSpec tracer

An error occurred while loading spec_helper.
Failure/Error: RSpecTracer.start

NoMethodError:
  undefined method `transform_keys!' for nil:NilClass
# ./spec/spec_helper.rb:22:in `<top (required)>'

Started RSpec tracer

An error occurred while loading rails_helper.
Failure/Error: RSpecTracer.start

NoMethodError:
  undefined method `transform_keys!' for nil:NilClass
# ./spec/spec_helper.rb:22:in `<top (required)>'
# ./spec/rails_helper.rb:7:in `<top (required)>'
No examples found.


Finished in 0.00008 seconds (files took 6.97 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples

Coverage report generated for RSpec to <...>/coverage. 681 / 915 LOC (74.43%) covered.
Lcov style coverage report generated for RSpec to <...>/coverage/lcov/coverage.lcov
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
```

## RSpec Tracer version

  ruby 2.6.6p146
  * rails (6.1.4.1)
  * rspec (3.10.0)
  * rspec-collection_matchers (1.2.0)
  * rspec-core (3.10.1)
  * rspec-expectations (3.10.1)
  * rspec-mocks (3.10.2)
  * rspec-nc (0.3.0)
  * rspec-rails (5.0.1)
  * rspec-support (3.10.2)
  * rspec-tracer (0.9.1)
  * rspec_junit_formatter (0.4.1)
  * simplecov (0.21.2)
  * simplecov-html (0.12.3)
  * simplecov-lcov (0.8.0)
  * simplecov_json_formatter (0.1.3)

**Comment by bopm** [comment]
Actually, you can reproduce it even easier. Press ctrl+c in the middle of the suite and your cache is totally broken the same way.

**Comment by avmnu-sng** [comment]
@bopm Could you try the latest release?

**Comment by bopm** [comment]
Yep, I tried that, and while it's no longer crushing after premature exit, seemingly it's no longer running any tests after that. I'll try to reproduce it early next week and will open a new issue if it is really like that. Thanks for all your effort, this project is something I was thinking about for a while.

**Comment by avmnu-sng** [comment]
If you interrupt the execution, it's RSpec expected behavior to finish up the ongoing example (not the suite) and then exit. Also, exiting from the `pry` session should continue to run all the examples. You can validate and confirm the behavior.
